server:
    port: 8001
spring:
    application:
        name: demo

# Prometheus
management:
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true
        enable:
            all=true: