server:
    port: 8001

spring:
    application:
        name: demo

management:
    endpoints:
        web:
            exposure:
                include: "*"      # expose all actuator endpoints
            base-path: /actuator
    endpoint:
        prometheus:
            enabled: true        # enable Prometheus endpoint
    metrics:
        export:
            prometheus:
                enabled: true      # allow metrics export to Prometheus
        enable:
            all: true            # enable all metrics
